version: '3.2'

services:
  angular-dev:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    restart: on-failure
    volumes:
      - .:/ng-app
    ports:
      - "2300:4200"
      - "49153:49153"
